-- Seed data generated from SBL_OASIS_SERVICES_PRICELIST.xlsx
-- Run once in the Supabase SQL Editor, after db/migrations/001_treatments_menu.sql.
-- Safe to re-run: clears existing rows in these categories first, so re-running
-- after fixing a typo in this file won't create duplicates.
--
-- Retail products (Body Butter, Body Oil, Face Soap, Glow Serum, Body Scrub,
-- Body Soap) from the "SBL PRODUCTS" section of the pricelist are deliberately
-- excluded — those live in the Skincare product catalog instead.

delete from treatments where category in ('Body Sculpting', 'Body Treatment', 'Counselling', 'Dental Care', 'Eyebrows', 'Eyelash Extensions', 'Facial Treatments', 'IV Therapy', 'Laser Treatment', 'Manicure', 'Massages', 'PRP Treatments', 'Pedicure', 'Private Care', 'Skin Consultation', 'Trainings & Workshops', 'Waxing');

insert into treatments (name, category, description, duration, price, is_featured, sort_order) values
  ('Classic Facials', 'Facial Treatments', '', null, 25000, false, 0),
  ('Brightening Facials', 'Facial Treatments', '', null, 30000, false, 1),
  ('Micro-Needling', 'Facial Treatments', '', null, 50000, false, 2),
  ('Acne Facials', 'Facial Treatments', '', null, 40000, false, 3),
  ('Anti-Ageing', 'Facial Treatments', '', null, 50000, false, 4),
  ('Hydra Facial', 'Facial Treatments', '', null, 40000, false, 5),
  ('Dermaplanning', 'Facial Treatments', '', null, 30000, false, 6),
  ('Microdermabrasion', 'Facial Treatments', '', null, 45000, false, 7),
  ('Deep Cleansing Facials', 'Facial Treatments', '', null, 30000, false, 8),
  ('BB Glow', 'Facial Treatments', '', null, 55000, false, 9),
  ('Chemical Peels', 'Facial Treatments', '', null, 75000, false, 10),
  ('Vampire Facials', 'Facial Treatments', '', null, 75000, false, 11),
  ('Carbon Laser Facials', 'Facial Treatments', '', null, 50000, false, 12),
  ('Mesotherapy/Skin Boosters', 'Facial Treatments', '', null, 70000, false, 13),
  ('Gentleman''s Facials (Classic)', 'Facial Treatments', '', null, 30000, false, 14),
  ('Gentleman''s Facials (Premium)', 'Facial Treatments', '', null, 40000, false, 15),
  ('Skin Analysis', 'Facial Treatments', '', null, 20000, false, 16),
  ('SBL Glow Facials', 'Facial Treatments', '', null, 100000, true, 17),
  ('Additional Dermaplanning (add-on to any facial)', 'Facial Treatments', '', null, 15000, false, 18),
  ('Relaxation Massage (Swedish) - Single', 'Massages', '', null, 30000, false, 0),
  ('Relaxation Massage (Swedish) - Couple', 'Massages', '', null, 55000, false, 1),
  ('Deep Tissue - Single', 'Massages', '', null, 35000, false, 2),
  ('Deep Tissue - Couple', 'Massages', '', null, 65000, false, 3),
  ('G5 Machine Massage', 'Massages', '', null, 50000, false, 4),
  ('Aromatherapy', 'Massages', '', null, 30000, false, 5),
  ('Hot Stone Massage', 'Massages', '', null, 40000, false, 6),
  ('Lymphatic Massage (Per Session)', 'Massages', '', null, 50000, false, 7),
  ('Pregnancy Massage (Per session)', 'Massages', '', null, 35000, false, 8),
  ('Physiotherapy (Per Session)', 'Massages', '', null, 35000, false, 9),
  ('Red Light therapy', 'Massages', '', null, 45000, false, 10),
  ('The Signature Duet', 'Massages', '', null, 70000, true, 11),
  ('Steam Bath', 'Body Treatment', '', null, 17500, false, 0),
  ('Body Scrub (Exfoliating)', 'Body Treatment', '', null, 50000, false, 1),
  ('Body Polish (Brightening)', 'Body Treatment', '', null, 60000, false, 2),
  ('Hamman / Brightening / Signature H', 'Body Treatment', 'Pricing varies by package — contact us for full details.', null, 60000, true, 3),
  ('Skin Tag/Mole Removal', 'Body Treatment', '', null, 30000, false, 4),
  ('Dry Pedicure', 'Pedicure', '', null, 5500, false, 0),
  ('Wet Pedicure', 'Pedicure', '', null, 15000, false, 1),
  ('Fungi Treatment', 'Pedicure', '', null, 15000, false, 2),
  ('Signature Pedicure', 'Pedicure', '', null, 20000, false, 3),
  ('Signature Paraffin Pedicure', 'Pedicure', '', null, 35000, false, 4),
  ('Grooming and Nail Polish', 'Manicure', '', null, 8000, false, 0),
  ('Signature Manicure', 'Manicure', '', null, 17500, false, 1),
  ('Signature Paraffin Manicure', 'Manicure', '', null, 25000, false, 2),
  ('Emsculpt', 'Body Sculpting', '', null, 50000, false, 0),
  ('Ultrasonic Cavitation, Radiofrequency', 'Body Sculpting', '', null, 85000, false, 1),
  ('Wood Therapy', 'Body Sculpting', '', null, 30000, false, 2),
  ('Glow Therapy', 'IV Therapy', '', null, 60000, false, 0),
  ('Immune Booster', 'IV Therapy', '', null, 30000, false, 1),
  ('Collagen Skin Repair', 'IV Therapy', '', null, 57500, false, 2),
  ('Libido Booster', 'IV Therapy', '', null, 40000, false, 3),
  ('Anti-Aging', 'IV Therapy', '', null, 50000, false, 4),
  ('Body Detox', 'IV Therapy', '', null, 40000, false, 5),
  ('Weight Management', 'IV Therapy', '', null, 80000, false, 6),
  ('SBL Luxe Infusion', 'IV Therapy', '', null, 120000, true, 7),
  ('Laser Hair Removal — Abdomen', 'Laser Treatment', '', null, 30000, false, 0),
  ('Laser Hair Removal — Chin', 'Laser Treatment', '', null, 35000, false, 1),
  ('Laser Hair Removal — Chest', 'Laser Treatment', '', null, 35000, false, 2),
  ('Laser Hair Removal — Bikini', 'Laser Treatment', '', null, 40000, false, 3),
  ('Laser Hair Removal — Brazilian', 'Laser Treatment', '', null, 55000, false, 4),
  ('Laser Hair Removal — Buttocks', 'Laser Treatment', '', null, 60000, false, 5),
  ('Laser Hair Removal — Half Arm', 'Laser Treatment', '', null, 40000, false, 6),
  ('Laser Hair Removal — Full Arm', 'Laser Treatment', '', null, 60000, false, 7),
  ('Laser Hair Removal — Underarm', 'Laser Treatment', '', null, 35000, false, 8),
  ('Laser Hair Removal — Half Legs', 'Laser Treatment', '', null, 50000, false, 9),
  ('Laser Hair Removal — Full Face', 'Laser Treatment', '', null, 55000, false, 10),
  ('Laser Hair Removal — Full Legs', 'Laser Treatment', '', null, 100000, false, 11),
  ('Laser Hair Removal — Full body', 'Laser Treatment', '', null, 270000, false, 12),
  ('Laser Tattoo Removal (starting from)', 'Laser Treatment', '', null, 50000, false, 13),
  ('Under Arm', 'Waxing', '', null, 10000, false, 0),
  ('Chin', 'Waxing', '', null, 7500, false, 1),
  ('Full Back', 'Waxing', '', null, 12000, false, 2),
  ('1/2 Leg', 'Waxing', '', null, 10000, false, 3),
  ('Full Leg', 'Waxing', '', null, 20000, false, 4),
  ('Chest', 'Waxing', '', null, 15000, false, 5),
  ('1/2 Arm', 'Waxing', '', null, 10000, false, 6),
  ('Full Arm', 'Waxing', '', null, 15000, false, 7),
  ('Bikini Line', 'Waxing', '', null, 15000, false, 8),
  ('Bikini with Trimming', 'Waxing', '', null, 22000, false, 9),
  ('Brazilian', 'Waxing', '', null, 20000, false, 10),
  ('Brazilian with Trimming', 'Waxing', '', null, 25000, false, 11),
  ('Eye Brow', 'Waxing', '', null, 7000, false, 12),
  ('Full Body', 'Waxing', '', null, 70000, false, 13),
  ('Hair Loss', 'PRP Treatments', '', null, 100000, false, 0),
  ('Under Eye', 'PRP Treatments', '', null, 70000, false, 1),
  ('o-Shot', 'PRP Treatments', '', null, 100000, false, 2),
  ('P-Shot', 'PRP Treatments', '', null, 150000, false, 3),
  ('Stretch Marks Treatment', 'PRP Treatments', '', null, 50000, false, 4),
  ('Teeth Whitening', 'Dental Care', '', null, 35000, false, 0),
  ('Teeth Scaling and Polishing', 'Dental Care', '', null, 50000, false, 1),
  ('Vagicials', 'Private Care', '', null, 25000, false, 0),
  ('Bumicals', 'Private Care', '', null, 30000, false, 1),
  ('Steaming', 'Private Care', '', null, 25000, false, 2),
  ('Tightening', 'Private Care', '', null, 100000, false, 3),
  ('Injection Lipolysis (Fat Dissolve) (starting from)', 'Private Care', '', null, 100000, false, 4),
  ('Microblading', 'Eyebrows', '', null, 45000, false, 0),
  ('Ombré', 'Eyebrows', '', null, 55000, false, 1),
  ('Combo', 'Eyebrows', '', null, 70000, false, 2),
  ('Tint', 'Eyebrows', '', null, 15000, false, 3),
  ('Grooming', 'Eyebrows', '', null, 20000, false, 4),
  ('Touch Up', 'Eyebrows', '', null, 35000, false, 5),
  ('Classic', 'Eyelash Extensions', '', null, 20000, false, 0),
  ('Volume', 'Eyelash Extensions', '', null, 30000, false, 1),
  ('Wispy', 'Eyelash Extensions', '', null, 50000, false, 2),
  ('Basic', 'Trainings & Workshops', '', null, null, false, 0),
  ('Intermediary', 'Trainings & Workshops', '', null, null, false, 1),
  ('Advanced', 'Trainings & Workshops', '', null, null, false, 2),
  ('Skin Consultation (20 Mins)', 'Skin Consultation', '', '20 Mins', 15000, false, 0),
  ('Skin Consultation (40 Mins)', 'Skin Consultation', '', '40 Mins', 30000, false, 1),
  ('Skin Consultation (60 Mins)', 'Skin Consultation', '', '60 Mins', 50000, false, 2),
  ('Counselling (30 Mins)', 'Counselling', '', '30 Mins', 20000, false, 0),
  ('Counselling (45 Mins)', 'Counselling', '', '45 Mins', 35000, false, 1),
  ('Counselling (60 Mins)', 'Counselling', '', '60 Mins', 55000, false, 2),
  ('Counselling (90 Mins)', 'Counselling', '', '90 Mins', 75000, false, 3),
  ('Extra Minutes (add-on)', 'Counselling', '', null, 5000, false, 4);
