/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as OasisRouteImport } from './routes/oasis'
import { Route as SkincareRouteImport } from './routes/skincare'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin/products/$productId'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminTreatmentsIndexRouteImport } from './routes/admin/treatments/index'
import { Route as AdminTreatmentsTreatmentIdRouteImport } from './routes/admin/treatments/$treatmentId'
import { Route as AdminTreatmentsNewRouteImport } from './routes/admin/treatments/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const OasisRoute = OasisRouteImport.update({
  id: '/oasis',
  path: '/oasis',
  getParentRoute: () => rootRouteImport,
} as any)
const SkincareRoute = SkincareRouteImport.update({
  id: '/skincare',
  path: '/skincare',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/admin/products/$productId',
  path: '/admin/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTreatmentsIndexRoute = AdminTreatmentsIndexRouteImport.update({
  id: '/admin/treatments/',
  path: '/admin/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTreatmentsTreatmentIdRoute =
  AdminTreatmentsTreatmentIdRouteImport.update({
    id: '/admin/treatments/$treatmentId',
    path: '/admin/treatments/$treatmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTreatmentsNewRoute = AdminTreatmentsNewRouteImport.update({
  id: '/admin/treatments/new',
  path: '/admin/treatments/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/oasis': typeof OasisRoute
  '/skincare': typeof SkincareRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/treatments/$treatmentId': typeof AdminTreatmentsTreatmentIdRoute
  '/admin/treatments/new': typeof AdminTreatmentsNewRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/treatments/': typeof AdminTreatmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/oasis': typeof OasisRoute
  '/skincare': typeof SkincareRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/treatments/$treatmentId': typeof AdminTreatmentsTreatmentIdRoute
  '/admin/treatments/new': typeof AdminTreatmentsNewRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/treatments': typeof AdminTreatmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/journal': typeof JournalRoute
  '/oasis': typeof OasisRoute
  '/skincare': typeof SkincareRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/treatments/$treatmentId': typeof AdminTreatmentsTreatmentIdRoute
  '/admin/treatments/new': typeof AdminTreatmentsNewRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/treatments/': typeof AdminTreatmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/journal'
    | '/oasis'
    | '/skincare'
    | '/admin/login'
    | '/admin/'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/treatments/$treatmentId'
    | '/admin/treatments/new'
    | '/admin/products/'
    | '/admin/treatments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/journal'
    | '/oasis'
    | '/skincare'
    | '/admin/login'
    | '/admin'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/treatments/$treatmentId'
    | '/admin/treatments/new'
    | '/admin/products'
    | '/admin/treatments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/journal'
    | '/oasis'
    | '/skincare'
    | '/admin/login'
    | '/admin/'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/treatments/$treatmentId'
    | '/admin/treatments/new'
    | '/admin/products/'
    | '/admin/treatments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  JournalRoute: typeof JournalRoute
  OasisRoute: typeof OasisRoute
  SkincareRoute: typeof SkincareRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminTreatmentsTreatmentIdRoute: typeof AdminTreatmentsTreatmentIdRoute
  AdminTreatmentsNewRoute: typeof AdminTreatmentsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminTreatmentsIndexRoute: typeof AdminTreatmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oasis': {
      id: '/oasis'
      path: '/oasis'
      fullPath: '/oasis'
      preLoaderRoute: typeof OasisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skincare': {
      id: '/skincare'
      path: '/skincare'
      fullPath: '/skincare'
      preLoaderRoute: typeof SkincareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/admin/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/treatments/': {
      id: '/admin/treatments/'
      path: '/admin/treatments'
      fullPath: '/admin/treatments/'
      preLoaderRoute: typeof AdminTreatmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/treatments/$treatmentId': {
      id: '/admin/treatments/$treatmentId'
      path: '/admin/treatments/$treatmentId'
      fullPath: '/admin/treatments/$treatmentId'
      preLoaderRoute: typeof AdminTreatmentsTreatmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/treatments/new': {
      id: '/admin/treatments/new'
      path: '/admin/treatments/new'
      fullPath: '/admin/treatments/new'
      preLoaderRoute: typeof AdminTreatmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  JournalRoute: JournalRoute,
  OasisRoute: OasisRoute,
  SkincareRoute: SkincareRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminTreatmentsTreatmentIdRoute: AdminTreatmentsTreatmentIdRoute,
  AdminTreatmentsNewRoute: AdminTreatmentsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminTreatmentsIndexRoute: AdminTreatmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
