/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OasisRouteImport } from './routes/oasis'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as JournalIndexRouteImport } from './routes/journal/index'
import { Route as JournalSlugRouteImport } from './routes/journal/$slug'
import { Route as SkincareIndexRouteImport } from './routes/skincare/index'
import { Route as SkincareProductIdRouteImport } from './routes/skincare/$productId'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin/bookings/index'
import { Route as AdminJournalIndexRouteImport } from './routes/admin/journal/index'
import { Route as AdminJournalPostIdRouteImport } from './routes/admin/journal/$postId'
import { Route as AdminJournalNewRouteImport } from './routes/admin/journal/new'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin/orders/index'
import { Route as AdminProductsIndexRouteImport } from './routes/admin/products/index'
import { Route as AdminProductsProductIdRouteImport } from './routes/admin/products/$productId'
import { Route as AdminProductsNewRouteImport } from './routes/admin/products/new'
import { Route as AdminTreatmentsIndexRouteImport } from './routes/admin/treatments/index'
import { Route as AdminTreatmentsTreatmentIdRouteImport } from './routes/admin/treatments/$treatmentId'
import { Route as AdminTreatmentsNewRouteImport } from './routes/admin/treatments/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OasisRoute = OasisRouteImport.update({
  id: '/oasis',
  path: '/oasis',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalIndexRoute = JournalIndexRouteImport.update({
  id: '/journal/',
  path: '/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalSlugRoute = JournalSlugRouteImport.update({
  id: '/journal/$slug',
  path: '/journal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SkincareIndexRoute = SkincareIndexRouteImport.update({
  id: '/skincare/',
  path: '/skincare/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkincareProductIdRoute = SkincareProductIdRouteImport.update({
  id: '/skincare/$productId',
  path: '/skincare/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/admin/bookings/',
  path: '/admin/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJournalIndexRoute = AdminJournalIndexRouteImport.update({
  id: '/admin/journal/',
  path: '/admin/journal/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJournalPostIdRoute = AdminJournalPostIdRouteImport.update({
  id: '/admin/journal/$postId',
  path: '/admin/journal/$postId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminJournalNewRoute = AdminJournalNewRouteImport.update({
  id: '/admin/journal/new',
  path: '/admin/journal/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/admin/products/',
  path: '/admin/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsProductIdRoute = AdminProductsProductIdRouteImport.update({
  id: '/admin/products/$productId',
  path: '/admin/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/admin/products/new',
  path: '/admin/products/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTreatmentsIndexRoute = AdminTreatmentsIndexRouteImport.update({
  id: '/admin/treatments/',
  path: '/admin/treatments/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTreatmentsTreatmentIdRoute =
  AdminTreatmentsTreatmentIdRouteImport.update({
    id: '/admin/treatments/$treatmentId',
    path: '/admin/treatments/$treatmentId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminTreatmentsNewRoute = AdminTreatmentsNewRouteImport.update({
  id: '/admin/treatments/new',
  path: '/admin/treatments/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/oasis': typeof OasisRoute
  '/returns': typeof ReturnsRoute
  '/admin/login': typeof AdminLoginRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/skincare/$productId': typeof SkincareProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/skincare/': typeof SkincareIndexRoute
  '/admin/journal/$postId': typeof AdminJournalPostIdRoute
  '/admin/journal/new': typeof AdminJournalNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/treatments/$treatmentId': typeof AdminTreatmentsTreatmentIdRoute
  '/admin/treatments/new': typeof AdminTreatmentsNewRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/journal/': typeof AdminJournalIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/treatments/': typeof AdminTreatmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/oasis': typeof OasisRoute
  '/returns': typeof ReturnsRoute
  '/admin/login': typeof AdminLoginRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/skincare/$productId': typeof SkincareProductIdRoute
  '/admin': typeof AdminIndexRoute
  '/journal': typeof JournalIndexRoute
  '/skincare': typeof SkincareIndexRoute
  '/admin/journal/$postId': typeof AdminJournalPostIdRoute
  '/admin/journal/new': typeof AdminJournalNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/treatments/$treatmentId': typeof AdminTreatmentsTreatmentIdRoute
  '/admin/treatments/new': typeof AdminTreatmentsNewRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/journal': typeof AdminJournalIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
  '/admin/treatments': typeof AdminTreatmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/oasis': typeof OasisRoute
  '/returns': typeof ReturnsRoute
  '/admin/login': typeof AdminLoginRoute
  '/journal/$slug': typeof JournalSlugRoute
  '/skincare/$productId': typeof SkincareProductIdRoute
  '/admin/': typeof AdminIndexRoute
  '/journal/': typeof JournalIndexRoute
  '/skincare/': typeof SkincareIndexRoute
  '/admin/journal/$postId': typeof AdminJournalPostIdRoute
  '/admin/journal/new': typeof AdminJournalNewRoute
  '/admin/products/$productId': typeof AdminProductsProductIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/admin/treatments/$treatmentId': typeof AdminTreatmentsTreatmentIdRoute
  '/admin/treatments/new': typeof AdminTreatmentsNewRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/journal/': typeof AdminJournalIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
  '/admin/treatments/': typeof AdminTreatmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/oasis'
    | '/returns'
    | '/admin/login'
    | '/journal/$slug'
    | '/skincare/$productId'
    | '/admin/'
    | '/journal/'
    | '/skincare/'
    | '/admin/journal/$postId'
    | '/admin/journal/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/treatments/$treatmentId'
    | '/admin/treatments/new'
    | '/admin/bookings/'
    | '/admin/journal/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/treatments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/oasis'
    | '/returns'
    | '/admin/login'
    | '/journal/$slug'
    | '/skincare/$productId'
    | '/admin'
    | '/journal'
    | '/skincare'
    | '/admin/journal/$postId'
    | '/admin/journal/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/treatments/$treatmentId'
    | '/admin/treatments/new'
    | '/admin/bookings'
    | '/admin/journal'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/treatments'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/faq'
    | '/oasis'
    | '/returns'
    | '/admin/login'
    | '/journal/$slug'
    | '/skincare/$productId'
    | '/admin/'
    | '/journal/'
    | '/skincare/'
    | '/admin/journal/$postId'
    | '/admin/journal/new'
    | '/admin/products/$productId'
    | '/admin/products/new'
    | '/admin/treatments/$treatmentId'
    | '/admin/treatments/new'
    | '/admin/bookings/'
    | '/admin/journal/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/treatments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  OasisRoute: typeof OasisRoute
  ReturnsRoute: typeof ReturnsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  JournalSlugRoute: typeof JournalSlugRoute
  SkincareProductIdRoute: typeof SkincareProductIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  JournalIndexRoute: typeof JournalIndexRoute
  SkincareIndexRoute: typeof SkincareIndexRoute
  AdminJournalPostIdRoute: typeof AdminJournalPostIdRoute
  AdminJournalNewRoute: typeof AdminJournalNewRoute
  AdminProductsProductIdRoute: typeof AdminProductsProductIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminTreatmentsTreatmentIdRoute: typeof AdminTreatmentsTreatmentIdRoute
  AdminTreatmentsNewRoute: typeof AdminTreatmentsNewRoute
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
  AdminJournalIndexRoute: typeof AdminJournalIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
  AdminTreatmentsIndexRoute: typeof AdminTreatmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oasis': {
      id: '/oasis'
      path: '/oasis'
      fullPath: '/oasis'
      preLoaderRoute: typeof OasisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/': {
      id: '/journal/'
      path: '/journal'
      fullPath: '/journal/'
      preLoaderRoute: typeof JournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal/$slug': {
      id: '/journal/$slug'
      path: '/journal/$slug'
      fullPath: '/journal/$slug'
      preLoaderRoute: typeof JournalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skincare/': {
      id: '/skincare/'
      path: '/skincare'
      fullPath: '/skincare/'
      preLoaderRoute: typeof SkincareIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skincare/$productId': {
      id: '/skincare/$productId'
      path: '/skincare/$productId'
      fullPath: '/skincare/$productId'
      preLoaderRoute: typeof SkincareProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/admin/bookings'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/journal/': {
      id: '/admin/journal/'
      path: '/admin/journal'
      fullPath: '/admin/journal/'
      preLoaderRoute: typeof AdminJournalIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/journal/$postId': {
      id: '/admin/journal/$postId'
      path: '/admin/journal/$postId'
      fullPath: '/admin/journal/$postId'
      preLoaderRoute: typeof AdminJournalPostIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/journal/new': {
      id: '/admin/journal/new'
      path: '/admin/journal/new'
      fullPath: '/admin/journal/new'
      preLoaderRoute: typeof AdminJournalNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/admin/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/$productId': {
      id: '/admin/products/$productId'
      path: '/admin/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/admin/products/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/treatments/': {
      id: '/admin/treatments/'
      path: '/admin/treatments'
      fullPath: '/admin/treatments/'
      preLoaderRoute: typeof AdminTreatmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/treatments/$treatmentId': {
      id: '/admin/treatments/$treatmentId'
      path: '/admin/treatments/$treatmentId'
      fullPath: '/admin/treatments/$treatmentId'
      preLoaderRoute: typeof AdminTreatmentsTreatmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/treatments/new': {
      id: '/admin/treatments/new'
      path: '/admin/treatments/new'
      fullPath: '/admin/treatments/new'
      preLoaderRoute: typeof AdminTreatmentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  OasisRoute: OasisRoute,
  ReturnsRoute: ReturnsRoute,
  AdminLoginRoute: AdminLoginRoute,
  JournalSlugRoute: JournalSlugRoute,
  SkincareProductIdRoute: SkincareProductIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  JournalIndexRoute: JournalIndexRoute,
  SkincareIndexRoute: SkincareIndexRoute,
  AdminJournalPostIdRoute: AdminJournalPostIdRoute,
  AdminJournalNewRoute: AdminJournalNewRoute,
  AdminProductsProductIdRoute: AdminProductsProductIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminTreatmentsTreatmentIdRoute: AdminTreatmentsTreatmentIdRoute,
  AdminTreatmentsNewRoute: AdminTreatmentsNewRoute,
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
  AdminJournalIndexRoute: AdminJournalIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
  AdminTreatmentsIndexRoute: AdminTreatmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
